# docker-compose.yml (run from the project root, alongside the Dockerfile folder)
version: "3.8"
services:
  channels-backend:
    image: fancybits/channels-dvr:latest
    container_name: channels-backend
    ports:
      - "8090:8089"               # Maps host 8090 -> container 8089 (Channels DVR web UI)
    environment:
      - TZ=America/New_York   # Set your timezone
    volumes:
      - ./channels-backend/config:/channels-dvr
      - ./channels-backend/recordings:/shares/DVR

  mapper:
    build: ./channels-dvr-mapper
    container_name: channels-mapper
    depends_on:
      - channels-backend
    ports:
      - "8080:80"                # Maps host 8080 -> container 80 (Channel-mapper UI)
    environment:
      - CHANNELS_BACKEND_IP=channels-backend:8089
    volumes:
      - ./channels-dvr-mapper:/var/www/html
